[package]
name = "h_type"
version = "0.1.0"
authors = ["chengkun <276128749@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
